### ISSUE TITLE
container example?

### ISSUE THREAD

**Issue by ruckc** [davmac314/dinit#25] opened 2019-12-24 13:24 UTC
I read your [blog post](https://davmac.wordpress.com/2019/12/18/escape-from-system-d-episode-vi-freedom-in-sight/), and was intrigued, i've been looking for a lightweight systemd replacement for containers, focusing on simple service management, without going back to sysvinit with shell scripts.

I tried using it as a general purpose service manager, to allow child containers to just copy in a /etc/dinit.d/boot, and let dinit just take over... but i'm getting "free(): invalid pointer" whenever trying to use /sbin/dinit as the container's PID 1.

Any suggestions?  I'm trying 0.8.0

**Comment by ruckc** [comment] 2019-12-24 14:45
in testing, my attempt at dinit scripts are https://github.com/ruckc/ubi8-services/tree/master/service/postgresql/dinit.d ... I was able to recreate the `free(): invalid pointer` with an invalid init script (that failed by `dinitcheck`) but dinitcheck shows these with no problems.

```
Checking service: boot...
Checking service: postgresql...
Checking service: pginit...
No problems found.
```

**Comment by davmac314** [comment] 2019-12-25 03:57
Hi! I believe this problem is caused by your `pginit` service which has no command specified. (That shouldn't cause a crash, so this is a bug that I will need to fix! But if you specify a command the problem should go away).

(This should also be picked up by `dinitcheck`, so that's another thing to fix).

Let me know if adding a command resolves the issue! Thanks.

**Comment by ruckc** [comment] 2019-12-26 20:41
that was it, the command was missing.  I was mainly focused on building out my thought process (pginit doing a one time initialization, and postgresql service doing the actual service execution), instead of trying to collapse it all down into one bash script.

**Comment by davmac314** [comment] 2019-12-27 11:25
Ok, thanks. The overall issue should be fixed by c55450f (now on master), but I won't close this issue until `dinitcheck` correctly reports the problem and there's a suitable test to make sure this doesn't crop up again.

**Comment by mskarbek** [comment] 2019-12-27 15:53
@ruckc you don't have to build `dinit`, there is a repo with Epel8/CentOS Stream support, works fine with `ubi` images - https://copr.fedorainfracloud.org/coprs/mskarbek/dinit/
If you see value in tracking the master branch then I can think about reviving https://copr.fedorainfracloud.org/coprs/mskarbek/dinit.dev/.
I'm using `dinit` with `fc30`, `fc31` and `el7` container images and maintain repo internally but I'll try to publish it to the COPR on time. ;)

**Comment by ruckc** [comment] 2019-12-28 22:21
So, that did work, but I'm unable to figure out why an error is occurring, primarily the `executing commandPermission denied`.  The /usr/local/bin/pginit is executable, and works properly with runuser - postgres -c "/usr/local/bin/pginit".  Additionally, I can't seem to figure out how to enable debugging, and `--log-file <filename>` never gets created if I try to run dinit manually.
```
$ podman run ruck-service-postgresql
dinit: pginit: execution failed - executing commandPermission denied
[FAILED] pginit
[FAILED] postgresql
[FAILED] boot
All services have stopped with no shutdown issued; boot failure?
Halting.
/sbin/shutdown: unrecognized option '--system'
```

**Comment by davmac314** [comment] 2019-12-29 01:15
Well, that's odd. I've fixed the error message on master already, it should say:
```
dinit: pginit: execution failed - executing command: Permission denied`
```
However, that message can only occur if the `exec` call failed, which is the very last step of executing the service process (relevant code is in run-child-proc.cc, in the `base_process_service::run_child_proc` function):

```
    err.stage = exec_stage::DO_EXEC;
    execvp(args[0], const_cast<char **>(args));
```
I.e. the "executing command" part of the error message corresponds to `err.stage = exec_stage::DO_EXEC` and this is the only place that `err.stage` is set to that value. It sounds like it's failing with `EPERM` ("Permission denied"). That's supposedly caused by one of the following:
```
       EPERM  The filesystem is mounted nosuid, the user is not the superuser,
              and the file has the set-user-ID or set-group-ID bit set.

       EPERM  The  process  is being traced, the user is not the superuser and
              the file has the set-user-ID or set-group-ID bit set.

       EPERM  A "capability-dumb" applications would not obtain the  full  set
              of  permitted  capabilities granted by the executable file.  See
              capabilities(7).
```
None of that explains anything much to me here, however; I doubt that any of those reasons apply.

I would suggest:

- trying it outside of the container, if that's feasible
- running `dinit` under `strace`, i.e:
   ```
   strace -f -o dinit-strace.log dinit
   ```
   This will let you make sure (by checking the generated log) that it is trying to execute the correct thing, at least.
 - check kernel output via `dmesg` after the failure to see if there is anything suspicious being logged at that level
 - try changing the command in the pginit service description to "/usr/bin/sleep 10" to see if that works, i.e. if it is something to do with the command itself.

Beyond that, there's not much I can think of.

I'm aware of the log file issue (log file won't be created if `dinit` doesn't actually start, as in this case) - I have a fix for that on my development branch. However, it wouldn't tell us much in this case, I think - all we know is that the `exec` call doesn't seem to be working (ideally we can verify that with `strace` as per above).

Regarding **scripted** vs **oneshot**, I believe **scripted** is correct here. You don't need to specify a stop-command and the service then effectively becomes a "run this command until it finishes" service.

**Comment by davmac314** [comment] 2020-01-01 09:23
I've released 0.8.1 which fixes the `free(): invalid pointer` and several other issues, so you might want to give that a try. However I'm still not clear on what's causing the Permission Denied for the `exec` call.

**Comment by mskarbek** [comment] 2020-01-01 13:26
@davmac314 0.8.1 archive does not contain top directory - small but annoying issue that forces a change in the package `spec` file

**Comment by davmac314** [comment] 2020-01-01 13:55
Ah, that's a mistake. Will correct it now, thanks.

**Comment by ruckc** [comment] 2020-01-02 13:57
the permission denied was my own stupidity, the run-as user couldn't execute the pginit script due to filemode of 0500.

Last potential issue, when stopping a container, dinit tries to call shutdown (with --system), is there anyway to disable this, and just let dinit exit(0)?

**Comment by davmac314** [comment] 2020-01-02 22:27
> when stopping a container, dinit tries to call shutdown (with --system), is there anyway to disable this, and just let dinit exit(0)?

Not at the moment, unfortunately - it's on the TODO list for the next release.

Glad that you figured out the other issue! I'll close this issue, but feel free to open another if you have any other issues.

**Closed by davmac314** 2020-01-02 22:27 UTC
