### ISSUE TITLE
service stop order

### ISSUE THREAD

**Issue by q66** [davmac314/dinit#127] opened 2022-11-20 14:56 UTC
right now dinit does not seem to guarantee any service stop order, from my testing; e.g. if i have a service A depend on B and dinit shuts down, A can easily stop after B (which is incorrect, because if A->B, the startup order is B first and then A, which means the stop order should be A and then B, as stopping B would mean stopping A's dependency). That means I can't have e.g. early services guarantee clean shutdown (stuff like shutting down LVM and unmounting filesystems in correct order - i.e. particularly for scripted oneshots) as they can race with other services for it.

**Comment by q66** [comment] 2022-11-20 14:57
this would be needed at least for hard dependencies, but maybe it would also be nice to try to ensure it for soft-dependencies (before/after/waits-for/etc)

**Comment by q66** [comment] 2022-11-20 15:30
otoh, handling these via stop-command is probably not the best idea either; stuff like lvm shutdown is best done once all services have been shut down - the dinit shutdown program performs some rudimentary cleanup (turns off swap and unmounts filesystems) but perhaps it should be able to execute some custom cleanup hooks where this can be performed? (other stuff could be put here, e.g. saving rng seed - and maybe it could actually not perform the swap/disk unmount by itself, but leave it to these hooks)

**Comment by davmac314** [comment] 2022-11-20 23:16
Dependent services are definitely supposed to stop before their dependees, so this sounds like a bug (maybe specific to shutdown). I'll see if I can reproduce.

**Comment by q66** [comment] 2022-11-21 01:17
makes sense

for the post-service-stop shutdown, i have introduced a workaround:

patch: https://github.com/chimera-linux/cports/blob/master/main/dinit/patches/shutdown-hook.patch
and then installed like: https://github.com/chimera-linux/dinit-chimera/blob/master/bin/shutdown

i'm not super happy with it and i'd rather not keep non-upstreamable workarounds around, got any ideas for something that would be satisfactory for upstream?

ideally this would all be managed through services, but that would require 1) being able to ensure stop ordering (i.e. this bug) 2) being able to have some scripted services run their stop commands after all non-pid1 processes have been terminated, which sounds like something that's not really possible with the current design

**Comment by davmac314** [comment] 2022-11-21 07:13
I guess it would be possible to add a service option (for scripted services) which means "kill any non-pid1 processes before running stop command". That feels a little hacky though (and it would probably have to force that service to wait for other services to stop first so it's not as simple implementation-wise as it could be).

Your shutdown-hook patch doesn't seem so bad really, so maybe I'll incorporate that (maybe just add some configurability, eg. where does it look for the hook, and possibly the ability to run multiple such hooks).

I will try to get to both issues in the next few days.

**Comment by q66** [comment] 2022-11-21 14:08
my main issue with this approach is that it's fundamentally inflexible:

1) i was thinking of having a custom user script (called e.g. `/etc/rc.shutdown` for familiarity) that runs after most services are down, but before killing non-pid1 processes
2) since the shutdown script runs as a part of the separate shutdown executable, it does not inherit the service manager's environment (which means stuff like container detection becomes clunky, which is very trivial in service environment)
3) i'm not a fan of how the final cleanup is not a part of the service stop flow, because it means that services get to perform init for some of these things, but the cleanup has to be performed in a script in a completely separate place

**Comment by davmac314** [comment] 2022-11-21 21:56
Could you have this (`/etc/rc.shutdown`) performed via the stop-command of a service? - you would need to have most other services depend on it, directly or indirectly, to control ordering (and if there is currently a bug in shutdown ordering then this needs to be fixed of course).

The separate system-level shutdown tasks could then be done as part of the shutdown hook (via the mechanism in the patch you have now, or similar).

**Comment by q66** [comment] 2022-11-21 22:11
i guess you are right for the first concern, and if the bug was to be fixed the dependency order is already addressed from my side - i recently did a large rework of the early services in dinit-chimera: https://github.com/chimera-linux/dinit-chimera/tree/master/system-services and as things are, these oneshots already have tight dependency relationships (as they are purely scripted/internal and therefore never meant to be stopped or restarted) and thus the first service to start should also be the last service to finish; every non-scripted regular service is meant to hard-depend on at least one of the targets by design (in most cases `init-local.target` is the one where all mandatory setup has been performed, but things are free to choose one of the earlier targets if there is value in allowing the daemon to start before that point)

**Comment by davmac314** [comment] 2022-11-24 08:09
Ordering issue should be fixed via 2ee11970c6fa1fad6c5db69bcb0d8cb611fc1a46

**Comment by davmac314** [comment] 2022-12-18 23:14
Sorry for the delay getting to the other part (shutdown hooks / running service shutdown after killing other processes). I have been thinking about this and oscillating between two alternatives - the hooks for shutdown, and a service option which specifies that all (non-dinit) processes should be killed before this service shutdown command is run.

Not that for the final unmounting, there is a reason this is done in a separate process than dinit. Specifically: when dinit runs, the kernel keeps the dinit executable file open (i.e. it memory-maps the file, which mean keeping it open). If the executable file is then deleted (say, dinit is upgraded to a newer version, so the old /sbin/dinit file is removed and a new one created in its place) then the kernel retains an open deleted file; an inode on the filesystem must be retained for that file and can only be removed when the file is actually closed. This state causes problems for unmounting (including for remounting read-only), because unmounting should leave the filesystem in a clean state (no inodes that aren't attached to a filename - otherwise, the space used by that file would remain consumed until you ran a filesystem check). By exec'ing another executable - in this case `shutdown` - the problem is solved; the kernel closes the file description referring to the deleted file, the root filesystem can be remounted readonly since the `shutdown` executable has certainly not been deleted.

So, unmount as part of shutdown (or part of a shutdown hook) needs to stay, unfortunately (although I note that there there is now a "lazy unmount" option might possibly solve the problem a different way, that will need testing).

I think I'm more and more leaning towards also having the service option (to kill other processes before running the service shutdown), since that allows much better symmetry for other services. The main downside is it requires a good deal of additional logic to nicely handle the case where the service hierarchy isn't set up for this, i.e. it's not ideal if this option causes a kill signal to be broadcast while other services are still shutting down. For now that can probably be pushed to the user - i.e. "if you use this option, responsibility is on you to make sure the service hierarchy is constructed such that no other services can be shutting down simultaneously" i.e. all the "kill broadcast" service must have all the pre-broadcast-shutdown services as dependencies. But ultimately, at least dinitcheck should warn if this option is used and the hierarchy is incorrect.

**Comment by q66** [comment] 2022-12-19 01:34
ah, i guess that makes sense, thanks for the detailed explanation

I've been busy working on things necessary to get alpha out for Chimera, but after that i will try to get back to working on some dinit enhancements i had in mind

**Comment by davmac314** [comment] 2023-01-07 01:56
This should all be addressed by 8dcf80ff67316b2afd1968d5c276f3e9718c52b4 and 2c50757365cfd44d3ee2c309953c4c4374f22d30, note the latter however is largely untested at this point.

**Closed** 2023-02-12 05:16 UTC
Labels: Question, A-Importance: Normal, C-dinit, C-dinit-service, Feature Request
